### ISSUE TITLE
prometheus url not support tls

### ISSUE THREAD

**Issue by garenwen** [Qihoo360/doraemon#10]
prometheus not support tls

**Comment by garenwen** [comment]
由于我们的prometheus是跨集群的，所有需要走公网，然后设置数据源的地方没法设置证书

**Comment by jayryu** [comment]
> 由于我们的prometheus是跨集群的，所有需要走公网，然后设置数据源的地方没法设置证书

官方文档上说prometheus并不直接支持tls认证，你们是使用nginx做反向代理加的证书吗？https://prometheus.io/docs/guides/tls-encryption/
