### ISSUE TITLE
alert-gateway报错,alert record写库失败

### ISSUE THREAD

**Issue by hanxinhisen** [Qihoo360/doraemon#15]
alert-gateway报错
`[alerts.go:566]  Insert alter failed:Error 1292: Incorrect datetime value: '0000-00-00' for column 'confirmed_at' at row 1`

doraemon/cmd/alert-gateway/models/alerts.go 文件中
`todayZero, _ := time.ParseInLocation("2006-01-02", "2019-01-01 15:22:22", time.Local)`

sql中定义的confirmed_at的类型为datetime

**Comment by jayryu** [comment]
请看 #8
