### ISSUE TITLE
支持配置basic-auth暴露到公网的prometheus吗？

### ISSUE THREAD

**Issue by 912988434** [Qihoo360/doraemon#17]
实际使用prometheus有时候会通过basic-auth暴露到公网，这种数据源添加支持认证吗？ 数据源地址可以下k8s集群内地址吗，比如  http://prometheus-k8s.monitoring.svc.cluster.local:9090吗？

**Comment by jayryu** [comment]
1.不支持
2.如果将哆啦A梦部署在k8s集群上是可以的

**Comment by jayryu** [comment]
1.不支持
2.如果将哆啦A梦部署在k8s集群上是可以的

**Comment by jayryu** [comment]
> 实际使用prometheus有时候会通过basic-auth暴露到公网，这种数据源添加支持认证吗？ 数据源地址可以下k8s集群内地址吗，比如 [http://prometheus-k8s.monitoring.svc.cluster.local:9090吗？](http://prometheus-k8s.monitoring.svc.cluster.local:9090%E5%90%97%EF%BC%9F)

1.不支持
2.如果将哆啦A梦部署在k8s集群上是可以的

**Comment by 70data** [comment]
https://github.com/Qihoo360/doraemon/issues/41
