### ISSUE TITLE
这块的代码是产品写的吗？

### ISSUE THREAD

**Issue by garenwen** [Qihoo360/doraemon#21]
https://github.com/Qihoo360/doraemon/blob/c7ce31fe720676330d75580d73b2b84d33bf0254/cmd/alert-gateway/models/alerts.go#L421
还是希望认真写一下，不行就做一下review

**Comment by garenwen** [comment]
基本不具备可读性

**Comment by jayryu** [comment]
> https://github.com/Qihoo360/doraemon/blob/c7ce31fe720676330d75580d73b2b84d33bf0254/cmd/alert-gateway/models/alerts.go#L421
> 
> 
> 还是希望认真写一下，不行就做一下review

有何建议?

**Comment by jayryu** [comment]
> https://github.com/Qihoo360/doraemon/blob/c7ce31fe720676330d75580d73b2b84d33bf0254/cmd/alert-gateway/models/alerts.go#L421
> 
> 
> 还是希望认真写一下，不行就做一下review

那块的代码逻辑有些复杂(与报警聚合相关)，具体实现可以参考一下这个ppt  https://slides.com/jayryu/deck-f2bffe  ，如果有好的建议欢迎分享或者提pr
