### ISSUE TITLE
告警恢复信息label的值为空

### ISSUE THREAD

**Issue by Chris0408** [Qihoo360/doraemon#22]
您好，本地跑了Doraemon的流程，感觉很不错，使用hook方式告警，告警恢复时post传过来的json 中label值一直为None,不知道是否是我哪里配置有问题？

**Comment by jayryu** [comment]
> 您好，本地跑了Doraemon的流程，感觉很不错，使用hook方式告警，告警恢复时post传过来的json 中label值一直为None,不知道是否是我哪里配置有问题？

经确认，是没有将最新后端镜像上传，之后会重新编译后端容器镜像，你也可以自己使用makefile来生成一个本地镜像，命令如下：make build-backend-image

**Comment by jayryu** [comment]
> 您好，本地跑了Doraemon的流程，感觉很不错，使用hook方式告警，告警恢复时post传过来的json 中label值一直为None,不知道是否是我哪里配置有问题？

已上传最新镜像，请下载使用最新镜像

**Comment by Chris0408** [comment]
好的，十分感谢，我在试试

**Comment by jayryu** [comment]
> 好的，十分感谢，我在试试

不客气哈，有问题请及时反馈~
