### ISSUE TITLE
是否会提供本地化部署方式

### ISSUE THREAD

**Issue by bob244** [Qihoo360/doraemon#24]
非常感谢。天下苦alertmanager久矣。
我想问的是未来是否会在 k8s和docker-compose以外提供本地化部署或者未来作为单一二进制文件。启动。
当然目前，我也可以直接按照compose里的写法，单独拿出来打包本地部署。
但是如果能有一份本地化部署的官方文档再好不过。
感谢。

**Comment by jayryu** [comment]
后续会提供的
