### ISSUE TITLE
告警异常

### ISSUE THREAD

**Issue by Chris0408** [Qihoo360/doraemon#28]
在使用过程中发现两个问题，麻烦看下是代码bug，还是我使用过程中配置有误

1.  采用HOOK邮件方式告警,  当告警项已恢复正常值，web界面也已显示告警已恢复，在prometheus web界面查询此时也是正常值，但是还是会不间断的收到告警邮件，告警信息中value值为第一次触发告警时的值。

2.  HOOK方式获取的告警发生时间和web界面显示的告警发生时间不同

告警规则和告警计划配置见下图
![1](https://user-images.githubusercontent.com/24953356/85981631-1bb3be00-ba17-11ea-9cc0-e2d33b8e9396.png)
![2](https://user-images.githubusercontent.com/24953356/85981646-1f474500-ba17-11ea-8986-ef81fc7c31b9.png)

**Comment by jayryu** [comment]
目前没有遇到过你所描述的情况，请提供详细信息，比如打印出hook所发出的post请求

**Comment by Chris0408** [comment]
经过测试发现是数据库的问题，我使用的是5.7.x版本的数据库，换了5.6.x与你们提供的数据库版本一致后正常了，建议在文档里说明一下数据库版本的问题，避免大家踩坑  : )

**Comment by jayryu** [comment]
> 经过测试发现是数据库的问题，我使用的是5.7.x版本的数据库，换了5.6.x与你们提供的数据库版本一致后正常了，建议在文档里说明一下数据库版本的问题，避免大家踩坑 : )

感谢反馈
