### ISSUE TITLE
push alerts 调用链的困惑

### ISSUE THREAD

**Issue by SenCoder** [Qihoo360/doraemon#32]
[Architecture](https://github.com/Qihoo360/doraemon/blob/master/docs/images/Architecture.png)

在如上链接的架构图中，有一条从 prometheus-server 指向 rule-engine 的调用链，备注为 "push alerts“， 我看 doraemon 的源码中 rule-engine 并没有启动服务。

请问，这条调用链是如何实现的？谢谢

**Comment by jayryu** [comment]
> [Architecture](https://github.com/Qihoo360/doraemon/blob/master/docs/images/Architecture.png)
> 
> 在如上链接的架构图中，有一条从 prometheus-server 指向 rule-engine 的调用链，备注为 "push alerts“， 我看 doraemon 的源码中 rule-engine 并没有启动服务。
> 
> 请问，这条调用链是如何实现的？谢谢

**Comment by jayryu** [comment]
> [Architecture](https://github.com/Qihoo360/doraemon/blob/master/docs/images/Architecture.png)
> 
> 在如上链接的架构图中，有一条从 prometheus-server 指向 rule-engine 的调用链，备注为 "push alerts“， 我看 doraemon 的源码中 rule-engine 并没有启动服务。
> 
> 请问，这条调用链是如何实现的？谢谢

其实是rule-engine向prometheus server发起一个query api的http请求，然后得到查询结果，这个图可能有些误导人，之后会改一下
