### ISSUE TITLE
k8s部署ingress访问入口

### ISSUE THREAD

**Issue by Ethan30k** [Qihoo360/doraemon#38]
我是k8s部署，我想使用Clusterip的service，通过ingress来访问。我把doraemon.yml改了几处地方
1、WebUrl = "http://doraemon.***.cn"

2、window.CONFIG = {
      baseURL: 'http://doraemon.***.cn',
    };

3、apiVersion: v1
kind: Service
metadata:
  labels:
    app: doraemon-web
  name: doraemon-web
  namespace: monitoring
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: doraemon-web

部署完毕，域名访问提示“”没有返回数据”
alertgateway容器日志报错：
2020/07/08 18:37:14.829 [C] [panic.go:522]  Handler crashed with error runtime error: invalid memory address or nil pointer dereference

请问是我哪里配置错误，还是现在只支持Nodeport模式的service访问

**Comment by SenCoder** [comment]
Ingress 没问题，这个可能是最近新提交的 ldap 功能，启动时发现配置中没有 ldap 相关的配置抛出的异常，随后修复

**Comment by jayryu** [comment]
> Ingress 没问题，这个可能是最近新提交的 ldap 功能，启动时发现配置中没有 ldap 相关的配置抛出的异常，随后修复

以后请验证无误后再提pr，不然会拒绝接受后续提交的pr

**Comment by jayryu** [comment]
> 我是k8s部署，我想使用Clusterip的service，通过ingress来访问。我把doraemon.yml改了几处地方
> 1、WebUrl = "http://doraemon.***.cn"
> 
> 2、window.CONFIG = {
> baseURL: 'http://doraemon.***.cn',
> };
> 
> 3、apiVersion: v1
> kind: Service
> metadata:
> labels:
> app: doraemon-web
> name: doraemon-web
> namespace: monitoring
> spec:
> ports:
> - protocol: TCP
> port: 8080
> targetPort: 80
> selector:
> app: doraemon-web
> 
> 部署完毕，域名访问提示“”没有返回数据”
> alertgateway容器日志报错：
> 2020/07/08 18:37:14.829 [C] [panic.go:522] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
> 
> 请问是我哪里配置错误，还是现在只支持Nodeport模式的service访问

请下载最新镜像，如有问题，请及时反馈

**Comment by Ethan30k** [comment]
> 请下载最新镜像，如有问题，请及时反馈

我更新了最新的镜像
![28D88A79-8B35-4301-BEE5-22A51AFD6FFD](https://user-images.githubusercontent.com/24836732/87004821-a1dabc00-c1f0-11ea-9a97-b561c1ddd617.png)
重新部署了deploy,还是一样
![2](https://user-images.githubusercontent.com/24836732/87004971-dea6b300-c1f0-11ea-92bc-936cd01b4b0d.jpg)
![3](https://user-images.githubusercontent.com/24836732/87004985-e2d2d080-c1f0-11ea-8359-75dcb5b4c2ad.jpg)

**Comment by jayryu** [comment]
> > 请下载最新镜像，如有问题，请及时反馈
> 
> 我更新了最新的镜像
> ![28D88A79-8B35-4301-BEE5-22A51AFD6FFD](https://user-images.githubusercontent.com/24836732/87004821-a1dabc00-c1f0-11ea-9a97-b561c1ddd617.png)
> 重新部署了deploy,还是一样
> ![2](https://user-images.githubusercontent.com/24836732/87004971-dea6b300-c1f0-11ea-92bc-936cd01b4b0d.jpg)
> ![3](https://user-images.githubusercontent.com/24836732/87004985-e2d2d080-c1f0-11ea-8359-75dcb5b4c2ad.jpg)

使用nodeport的方式是否可以成功访问？

**Comment by Ethan30k** [comment]
刚刚改成nodeport模式试了，前面放了个Nginx转发，其他配置和上面是一样的，还是不行

**Comment by jayryu** [comment]
> 刚刚改成nodeport模式试了，前面放了个Nginx转发，其他配置和上面是一样的，还是不行

可以进群加好友说明一下情况

![](https://user-images.githubusercontent.com/56525134/87225595-e7e67a00-c3c0-11ea-8348-be08e722a1a6.png)

**Comment by wutianya** [comment]
我也遇到同样的问题
