### ISSUE TITLE
no LDAP authentication method

### ISSUE THREAD

**Issue by OpenAndrus** [Qihoo360/doraemon#4]
Hi there, 
   I'm testing this project in local environment. After manually enabling ldap auth on frontend app(by editing(doraemon/web/app/page/base/app/login.js, changing chooseMethod from 'local' to 'ldap'), the backend log showing ' nomatch| POST     /api/v1/login/ldap'.
Then I dig into the backend code in file named 'cmd/alert-gateway/controllers/login.go', it turns out that there was not // @router /ldap [post] and ldap authentication code there.

So LDAP authentication is in both your roadmap, config file and documents, but just not implemented yet. I'm I right?

Thanks for your works, good idea and its helpful by the way.

**Comment by 70data** [comment]
Ldap is not currently supported, but will be.

**Comment by 70data** [comment]
https://github.com/Qihoo360/doraemon/pull/35
