### ISSUE TITLE
hook 方式方式告警是不是缺少了 描述

### ISSUE THREAD

**Issue by lizeyun** [Qihoo360/doraemon#42]
![image](https://user-images.githubusercontent.com/19726385/87405297-d46e2580-c5f1-11ea-8b6b-234a4904acda.png)
这个参数description 没有在告警post 的数据中体现出来

![image](https://user-images.githubusercontent.com/19726385/87405265-c5877300-c5f1-11ea-982c-763df9f118f5.png)

**Comment by jayryu** [comment]
> ![image](https://user-images.githubusercontent.com/19726385/87405297-d46e2580-c5f1-11ea-8b6b-234a4904acda.png)
> 这个参数description 没有在告警post 的数据中体现出来
> 
> ![image](https://user-images.githubusercontent.com/19726385/87405265-c5877300-c5f1-11ea-982c-763df9f118f5.png)

后续会加上描述

**Comment by jayryu** [comment]
> ![image](https://user-images.githubusercontent.com/19726385/87405297-d46e2580-c5f1-11ea-8b6b-234a4904acda.png)
> 这个参数description 没有在告警post 的数据中体现出来
> 
> ![image](https://user-images.githubusercontent.com/19726385/87405265-c5877300-c5f1-11ea-982c-763df9f118f5.png)

已添加，请下载最新镜像

**Comment by lizeyun** [comment]
谢谢，很好的东西

**Comment by jayryu** [comment]
> 谢谢，很好的东西

hi，请更新下最新镜像，昨天上传的镜像有个死锁的bug，会造成rule-engine返回的报警无法插入数据库，现已修复

**Comment by lizeyun** [comment]
> > 谢谢，很好的东西
> 
> hi，请更新下最新镜像，昨天上传的镜像有个死锁的bug，会造成rule-engine返回的报警无法插入数据库，现已修复

好吧，我刚刚还在郁闷怎么回事了，谢谢
