### ISSUE TITLE
doraemon-frontend一直Restarting

### ISSUE THREAD

**Issue by golang1999** [Qihoo360/doraemon#44]
dockercompose_doraemon-frontend_1   /usr/local/openresty/bin/o ...   Restarting   
doraemon-frontend一直Restarting

尝试手工打包build/frontend/Dockerfile 
修改openresty/openresty:1.15.8.1-1-centos  为 openresty/openresty:1.17.8.1-0-centos

问题解决。

**Comment by jayryu** [comment]
> dockercompose_doraemon-frontend_1 /usr/local/openresty/bin/o ... Restarting
> doraemon-frontend一直Restarting
> 
> 尝试手工打包build/frontend/Dockerfile
> 修改openresty/openresty:1.15.8.1-1-centos 为 openresty/openresty:1.17.8.1-0-centos
> 
> 问题解决。

目前 git上的代码未更新（没有最新功能），不要手动打包，请直接使用官方镜像
