### ISSUE TITLE
doraemon-backend容器一直重启

### ISSUE THREAD

**Issue by chengtianfa** [Qihoo360/doraemon#49]
选择告警通知方式为hook, 填入接口url后，doraemon-backend容器就一直重启，选择其它告警通知方式没有这种情况。

**Comment by jayryu** [comment]
> 选择告警通知方式为hook, 填入接口url后，doraemon-backend容器就一直重启，选择其它告警通知方式没有这种情况。

没有遇到过类似情况，有其他信息吗，或者进群反馈
![image](https://user-images.githubusercontent.com/56525134/88125087-1d7d3580-cc01-11ea-9a3a-fa031a6d7e79.png)

**Comment by chengtianfa** [comment]
2020/07/20 11:52:52.439 ESC[1;34m[I]reated by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:770 +0xd8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x969ab0]

goroutine 38 [running]:
github.com/Qihoo360/doraemon/cmd/alert-gateway/models.SendAlertsFor(0xc00020d410, 0xc00020d330, 0x1, 0xc00020da00)
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/models/groups.go:81 +0x9a0
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.Filter(0xc00020dd98, 0xc00020dd68, 0xc0000647e0, 0xc00020dca0)
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:481 +0x1316
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5.2(0xc000191b00, 0x13, 0xc0000647e0)
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:792 +0x518
created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:770 +0xd8
mESC[0m [controller.go:218]  [{2020-07-17 17:30:37.430944125 +0800 CST { 内存使用量 1} 2020-07-17 17:31:37.430944125 +0800 CST map[hh3cEntityExtPhysicalIndex:11 instance:xxx.xxx.xxx.xxx job:snmp] 2020-07-20 11:52:52.430944125 +0800 CST 0001-01-01 00:00:00 +0000 UTC 2 2020-07-20 11:55:52.430944125 +0800 CST 82}]

:panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x969ab0]

goroutine 64 [running]:
github.com/Qihoo360/doraemon/cmd/alert-gateway/models.SendAlertsFor(0xc0002ed410, 0xc0002ed330, 0x1, 0xc0002eda00)
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/models/groups.go:81 +0x9a0
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.Filter(0xc0002edd98, 0xc0002edd68, 0xc000064cc0, 0xc0000bdca0)
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:481 +0x1316
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5.2(0xc0002e0f80, 0x13, 0xc000064cc0)
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:792 +0x518
created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5
        /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:770 +0xd8
