### ISSUE TITLE
Full support for database migration

### ISSUE THREAD

**Issue by lujiajing1126** [Qihoo360/doraemon#5]
For now, the project initializes tables iff the database does not exist.

However, in some scenarios, the database is already created by DBA, in particular in the production environment. So I suppose we need a full support for data migration from creating database, creating skeletons of the tables to fulfilling necessary data.

With `beego migrate` subcommand, it can be done with ease.

**Comment by jayryu** [comment]
see here https://github.com/Qihoo360/doraemon/blob/master/docs/InitMysq-CN.md

**Comment by jayryu** [comment]
> For now, the project initializes tables iff the database does not exist.
> 
> However, in some scenarios, the database is already created by DBA, in particular in the production environment. So I suppose we need a full support for data migration from creating database, creating skeletons of the tables to fulfilling necessary data.
> 
> With `beego migrate` subcommand, it can be done with ease.

see here https://github.com/Qihoo360/doraemon/blob/master/docs/InitMysq-CN.md
