### ISSUE TITLE
发送告警的时候,alert-gateway报错了

### ISSUE THREAD

**Issue by xing-shadow** [Qihoo360/doraemon#52]
2020/07/24 11:48:22.738 [E] [alerts.go:482]  Insert alter failed:Error 1292: Incorrect datetime value: '0000-00-00' for column 'confirmed_at' at row 1

**Comment by jayryu** [comment]
> 2020/07/24 11:48:22.738 [E] [alerts.go:482] Insert alter failed:Error 1292: Incorrect datetime value: '0000-00-00' for column 'confirmed_at' at row 1

请看 #8
