### ISSUE TITLE
安装完以后，界面操作有问题

### ISSUE THREAD

**Issue by sun642514265** [Qihoo360/doraemon#57]
安装方式：docker

问题现象：
（1）docker方式安装完以后，通过地址登录，但是没有输入“用户名”和“密码”的地方。
（2）点击其他功能按钮，没有任何反应。

建议：能否在文档中体现如何拍错的过程呢？

**Comment by sun642514265** [comment]
（3）左侧下拉列表中的“本地用户账户管理” 也无法点击。

**Comment by sun642514265** [comment]
![1](https://user-images.githubusercontent.com/54477096/88787710-e55c9080-d1c6-11ea-95b7-4b2c3a8429d8.png)
![2](https://user-images.githubusercontent.com/54477096/88787717-e7265400-d1c6-11ea-8986-be0646a7fbc5.png)
![3](https://user-images.githubusercontent.com/54477096/88787725-e8f01780-d1c6-11ea-889d-2c9e95b024b5.png)

**Comment by sun642514265** [comment]
目前看到的现象，好像是数据库坏了，我转到自建数据库试试

**Comment by jayryu** [comment]
> 安装方式：docker
> 
> 问题现象：
> （1）docker方式安装完以后，通过地址登录，但是没有输入“用户名”和“密码”的地方。
> （2）点击其他功能按钮，没有任何反应。
> 
> 建议：能否在文档中体现如何拍错的过程呢？

这是由于web前端无法正常和后端进行通信的原因，请检查你的配置（可以通过chrome浏览器的console查看）

**Comment by sun642514265** [comment]
多谢大神解惑 和 提供查看问题方法，通过console 查看，的确是前端无法访问后端导致的，现在问题解决了。

**Comment by jetaime-chen** [comment]
docker 部署的，修改哪里可处理无法访问后端，现在访问后端的地址是 localhost:8080的问题，谢谢。

**Comment by jayryu** [comment]
> docker 部署的，修改哪里可处理无法访问后端，现在访问后端的地址是 localhost:8080的问题，谢谢。

deployments/docker-compose/conf/config.js中的"localhost"
