### ISSUE TITLE
请问下有交流群吗？

### ISSUE THREAD

**Issue by jinnzy** [Qihoo360/doraemon#59]
不好意思，看了各个地方好像都没有群连接，所以开了一个issues问一下。

**Comment by jayryu** [comment]
> 不好意思，看了各个地方好像都没有群连接，所以开了一个issues问一下。

![mmqrcode1595339654871](https://user-images.githubusercontent.com/56525134/89555462-aa033700-d842-11ea-8743-4defe09d3fc3.png)

**Comment by hutaishi** [comment]
可以再分享一下吗？这个分享已经过期

**Comment by jayryu** [comment]
> 不好意思，看了各个地方好像都没有群连接，所以开了一个issues问一下。

加我微信
![image](https://user-images.githubusercontent.com/56525134/89605602-8969ca00-d8a0-11ea-92cc-d658de2a3843.png)

**Comment by jinnzy** [comment]
> > 不好意思，看了各个地方好像都没有群连接，所以开了一个issues问一下。
> 
> 加我微信
> ![image](https://user-images.githubusercontent.com/56525134/89605602-8969ca00-d8a0-11ea-92cc-d658de2a3843.png)

谢谢
