### ISSUE TITLE
跨域问题，nginx配置无效，新版本在哪里可以下载？

### ISSUE THREAD

**Issue by dok8s** [Qihoo360/doraemon#64]
配置nginx代理也无效
![image](https://user-images.githubusercontent.com/24632466/89857775-8425bb80-dbcf-11ea-89c9-90f391b3510a.png)

**Comment by jayryu** [comment]
> 配置nginx代理也无效
> ![image](https://user-images.githubusercontent.com/24632466/89857775-8425bb80-dbcf-11ea-89c9-90f391b3510a.png)

直接拉取latest镜像即可，请使用wiki文档中的部署方式

**Comment by dok8s** [comment]
![image](https://user-images.githubusercontent.com/24632466/89858487-6b1e0a00-dbd1-11ea-937b-7eaa1a184c1e.png)
是通过docker-composer部署的，之前拉取的镜像都是latest

**Comment by Diors-Po** [comment]
拉取最新docker镜像，使用docker-compose方式部署，仍然存在跨域问题
