### ISSUE TITLE
kubernetes启动，web不断重启

### ISSUE THREAD

**Issue by superliu0** [Qihoo360/doraemon#66]
日志如下：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x969ab0]

**Comment by superliu0** [comment]
添加一条报警规则，后面不断触发报警，程序就会重启，删除规则后就不重启了

**Comment by jayryu** [comment]
> 添加一条报警规则，后面不断触发报警，程序就会重启，删除规则后就不重启了

是否在报警策略中配置了odingroup，如果配置了请删除该配置
