### ISSUE TITLE
Insert alter failed数组越界

### ISSUE THREAD

**Issue by echophlin** [Qihoo360/doraemon#71]
当我配置rabbitmq告警后，会出现如下数据越界的报错，其他中间件的告警规则看起来就不会出现，请问下要怎么解决
2020/09/03 10:12:37.994 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:37.998 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.001 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.004 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.008 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.012 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.015 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.019 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.022 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.026 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.029 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.033 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.036 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.039 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.043 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.046 [E] [alerts.go:667]  Insert alter failed:Error 1062: Duplicate entry '74-clusterrabbit@do-ns-dev-ops-rabbitmq-172-19-0-122durablefa' for key 'ruleid_labels_firedat'
2020/09/03 10:12:38.047 [D] [server.go:2774]  |      127.0.0.1| 200 | 305.073647ms|   match| POST     /api/v1/alerts   r:/api/v1/alerts/
panic: runtime error: index out of range
goroutine 31 [running]:
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.Filter(0xc00038bd98, 0xc00038bd68, 0xc00017c120, 0xc0001ee070)
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:353 +0x31d6
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5.2(0xc000258000, 0x13, 0xc00017c120)
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:792 +0x518
created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:770 +0xd8

**Comment by jayryu** [comment]
> 当我配置rabbitmq告警后，会出现如下数据越界的报错，其他中间件的告警规则看起来就不会出现，请问下要怎么解决
> 2020/09/03 10:12:37.994 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:37.998 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.001 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.004 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.008 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.012 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.015 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.019 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.022 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.026 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.029 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.033 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.036 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.039 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.043 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.046 [E] [alerts.go:667] Insert alter failed:Error 1062: Duplicate entry '74-cluster�rabbit@do-ns-dev-ops-rabbitmq-172-19-0-122�durable�fa' for key 'ruleid_labels_firedat'
> 2020/09/03 10:12:38.047 [D] [server.go:2774] | 127.0.0.1| 200 | 305.073647ms| match| POST /api/v1/alerts r:/api/v1/alerts/
> panic: runtime error: index out of range
> goroutine 31 [running]:
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.Filter(0xc00038bd98, 0xc00038bd68, 0xc00017c120, 0xc0001ee070)
> /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:353 +0x31d6
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5.2(0xc000258000, 0x13, 0xc00017c120)
> /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:792 +0x518
> created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.InitTimer.func5
> /go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:770 +0xd8

rabbitmq报警的相关label中有特殊字符，请去掉label的特殊字符

**Comment by echophlin** [comment]
大概理清楚了一些，
lebels包含@，/这些符号就会触发有数组越界的问题，哆啦A梦会不断崩溃。
lebels超过varchar(255)程序会自动截断（lebels字段在建表的时候是255，想尝试改大，但发现这个表加了几个索引，已经不能增大），哆啦A梦不会崩溃，使字符不会超过255，但是后面有些字段就不会拿到，就会丢告警。

**Comment by jayryu** [comment]
> 大概理清楚了一些，
> lebels包含@，/这些符号就会触发有数组越界的问题，哆啦A梦会不断崩溃。
> lebels超过varchar(255)程序会自动截断（lebels字段在建表的时候是255，想尝试改大，但发现这个表加了几个索引，已经不能增大），哆啦A梦不会崩溃，使字符不会超过255，但是后面有些字段就不会拿到，就会丢告警。

仔细看了下，不是特殊字符的问题，可以包含特殊字符@,/等等，但是不能超长，不超过255，超过截断后有的key就没有value了，在进行分割时就会报错，产生数组越界的问题
