### ISSUE TITLE
告警计划通过HOOK URL发送，但是告警恢复却没有走HOOK URL

### ISSUE THREAD

**Issue by nowindnowave** [Qihoo360/doraemon#75]
告警是正常的，告警恢复没有走HOOK URL，告警恢复时HOOK URL没接收到任何请求，在界面查看历史告警才能看到告警已恢复。

**Comment by jayryu** [comment]
> 告警是正常的，告警恢复没有走HOOK URL，告警恢复时HOOK URL没接收到任何请求，在界面查看历史告警才能看到告警已恢复。

应该是正常的，因为报警是每分钟的整点从数据库中进行扫描，然后发出的，如果一个报警在00:00:30的时候触发，但是在00:00:35就恢复了，那在下一分钟进行扫描的时候（00:01:00），就不会发出该报警

**Comment by xphzzxpp** [comment]
> 告警是正常的，告警恢复没有走HOOK URL，告警恢复时HOOK URL没接收到任何请求，在界面查看历史告警才能看到告警已恢复。

你好 请问你的hook URL如何配置的 文档没有看到约定参数名称  post参数如何传递

**Comment by nowindnowave** [comment]
谢谢回复，已经抓到恢复请求了，现在已正常
