### ISSUE TITLE
当我验证一条规则的时候，遇到了如下错误

### ISSUE THREAD

**Issue by eryajf** [Qihoo360/doraemon#8]
为了验证告警流程，我创建了一条规则，监控主机的node是否up，当我把node_exporter停掉之后，在告警历史中看不到任何记录，从gateway日志当中看到了如下错误：

```
2020/05/25 15:35:20.049 [I] [controller.go:218]  [{2020-05-25 15:27:35.044897044 +0800 CST {主机exporter无响应 主机exporter无响应 871} 2020-05-25 15:27:50.044897044 +0800 CST map[instance:192.168.0.2:9100 job:ops-eryajf-test-1] 2020-05-25 15:35:20.044897044 +0800 CST 0001-01-01 00:00:00 +0000 UTC 2 2020-05-25 15:38:20.044897044 +0800 CST 0}]

2020/05/25 15:35:20.050 [E] [alerts.go:566]  Insert alter failed:Error 1292: Incorrect datetime value: '0000-00-00' for column 'confirmed_at' at row 1
2020/05/25 15:35:20.050 [D] [server.go:2774]  |     172.19.0.4| 200 |   1.029839ms|   match| POST     /api/v1/alerts   r:/api/v1/alerts/
2020/05/25 15:35:30.322 [E] [panic.go:522]  Panic in UpdateMaintainlist:runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.UpdateMaintainlist.func1()
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:46 +0xb5
panic(0xa10f00, 0xffd010)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.UpdateMaintainlist()
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:69 +0x9c1
github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.init.1.func1()
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:399 +0x64
created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.init.1
	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:395 +0x35
```

我导入的是文档中提供的sql。

**Comment by jayryu** [comment]
> 为了验证告警流程，我创建了一条规则，监控主机的node是否up，当我把node_exporter停掉之后，在告警历史中看不到任何记录，从gateway日志当中看到了如下错误：
> 
> ```
> 2020/05/25 15:35:20.049 [I] [controller.go:218]  [{2020-05-25 15:27:35.044897044 +0800 CST {主机exporter无响应 主机exporter无响应 871} 2020-05-25 15:27:50.044897044 +0800 CST map[instance:192.168.0.2:9100 job:ops-eryajf-test-1] 2020-05-25 15:35:20.044897044 +0800 CST 0001-01-01 00:00:00 +0000 UTC 2 2020-05-25 15:38:20.044897044 +0800 CST 0}]
> 
> 2020/05/25 15:35:20.050 [E] [alerts.go:566]  Insert alter failed:Error 1292: Incorrect datetime value: '0000-00-00' for column 'confirmed_at' at row 1
> 2020/05/25 15:35:20.050 [D] [server.go:2774]  |     172.19.0.4| 200 |   1.029839ms|   match| POST     /api/v1/alerts   r:/api/v1/alerts/
> 2020/05/25 15:35:30.322 [E] [panic.go:522]  Panic in UpdateMaintainlist:runtime error: invalid memory address or nil pointer dereference
> goroutine 11 [running]:
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.UpdateMaintainlist.func1()
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:46 +0xb5
> panic(0xa10f00, 0xffd010)
> 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.UpdateMaintainlist()
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:69 +0x9c1
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.init.1.func1()
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:399 +0x64
> created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.init.1
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:395 +0x35
> ```
> 
> 我导入的是文档中提供的sql。

该问题已修复，请下载最新镜像

**Comment by jayryu** [comment]
> 为了验证告警流程，我创建了一条规则，监控主机的node是否up，当我把node_exporter停掉之后，在告警历史中看不到任何记录，从gateway日志当中看到了如下错误：
> 
> ```
> 2020/05/25 15:35:20.049 [I] [controller.go:218]  [{2020-05-25 15:27:35.044897044 +0800 CST {主机exporter无响应 主机exporter无响应 871} 2020-05-25 15:27:50.044897044 +0800 CST map[instance:192.168.0.2:9100 job:ops-eryajf-test-1] 2020-05-25 15:35:20.044897044 +0800 CST 0001-01-01 00:00:00 +0000 UTC 2 2020-05-25 15:38:20.044897044 +0800 CST 0}]
> 
> 2020/05/25 15:35:20.050 [E] [alerts.go:566]  Insert alter failed:Error 1292: Incorrect datetime value: '0000-00-00' for column 'confirmed_at' at row 1
> 2020/05/25 15:35:20.050 [D] [server.go:2774]  |     172.19.0.4| 200 |   1.029839ms|   match| POST     /api/v1/alerts   r:/api/v1/alerts/
> 2020/05/25 15:35:30.322 [E] [panic.go:522]  Panic in UpdateMaintainlist:runtime error: invalid memory address or nil pointer dereference
> goroutine 11 [running]:
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.UpdateMaintainlist.func1()
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:46 +0xb5
> panic(0xa10f00, 0xffd010)
> 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.UpdateMaintainlist()
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:69 +0x9c1
> github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.init.1.func1()
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:399 +0x64
> created by github.com/Qihoo360/doraemon/cmd/alert-gateway/initial.init.1
> 	/go/src/github.com/Qihoo360/doraemon/cmd/alert-gateway/initial/timer.go:395 +0x35
> ```
> 
> 我导入的是文档中提供的sql。

mysql insert 有一个时间字段，'0000-00-00 00:00:00'格式为这样。插入的是报错
ERROR 1292 (22007): Incorrect datetime value: '0000-00-00 00:00:00' for column 'return_create_time' at row 1
mysql允许将’0000-00-00’保存为“伪日期”,如果不使用no_zero_date sql模式。

root@localhost :(none)03:38:46>show variables like 'sql_mode';

+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| variable_name | value                                                                                                                                                                                        |
+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode        | strict_trans_tables,no_zero_in_date,no_zero_date,error_for_division_by_zero,no_auto_create_user,no_engine_substitution |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

参数中含有:  no_zero_date
解决办法： 去掉 no_zero_date 

set global sql_mode='strict_trans_tables,no_zero_in_date,error_for_division_by_zero,no_auto_create_user,no_engine_substitution';

如果不生效修改配置文件重新启动数据库。

原文见：https://blog.csdn.net/zhengwei125/article/details/79003563/

另外，请下载最新镜像

**Comment by eryajf** [comment]
感谢回复，当前已经可以看到相对应的告警了。
另外有个小建议，代码是否可以版本化，对应的镜像也可以同步版本号，不然镜像总是用默认的，将会不便于体验使用。

**Comment by jayryu** [comment]
> 感谢回复，当前已经可以看到相对应的告警了。
> 另外有个小建议，代码是否可以版本化，对应的镜像也可以同步版本号，不然镜像总是用默认的，将会不便于体验使用。

之后会采纳你的建议
