### ISSUE TITLE
告警规则修改不生效

### ISSUE THREAD

**Issue by FangPengbo** [Qihoo360/doraemon#85]
@70data @welefen 
您好:
告警规则修改之后阈值不生效
随后删除掉RuleID为x的规则 重新创建RuleID为y的规则
查看历史报警信息仍然是RuleID为x的规则在生效

**Comment by huangwei2013** [comment]
可以从两方面去查
1.手动调用 GET http://[IP:PORT]/api/v1/rules ，核对rule数据
2.查看 rule-engine 运行日志（如果看不到日志，可以让它指向一个无效的promethues地址，应该会有包括rule的错误提示）

**Comment by jayryu** [comment]
> @70data @welefen
> 您好:
> 告警规则修改之后阈值不生效
> 随后删除掉RuleID为x的规则 重新创建RuleID为y的规则
> 查看历史报警信息仍然是RuleID为x的规则在生效

需要把alerts表中旧的报警删除
