### ISSUE TITLE
在云主机上搭建环境，前端报错 net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by Jeremy-boo** [Qihoo360/doraemon#9]
环境： ucloud主机+docker-compose
环境搭建好后，访问首页出现如下错误：

error {data: "", msg: "服务器连接超时", code: -1}
2client.ad01.js:1 dark
vendor.dll.js:1 GET http://10.9.170.80:8080/api/v1/login/method net::ERR_CONNECTION_TIMED_OUT

注：已配网络规则

**Comment by jayryu** [comment]
> 环境： ucloud主机+docker-compose
> 环境搭建好后，访问首页出现如下错误：
> 
> error {data: "", msg: "服务器连接超时", code: -1}
> 2client.ad01.js:1 dark
> vendor.dll.js:1 GET http://10.9.170.80:8080/api/v1/login/method net::ERR_CONNECTION_TIMED_OUT
> 
> 注：已配网络规则

网络原因，请排查网络环境
