### ISSUE TITLE
alert-gateway容器60秒重启一次

### ISSUE THREAD

**Issue by 231bobo** [Qihoo360/doraemon#91]
你好，运行方式为docker-compose ，之前运行好好的，最近两天发现alert-gateway容器60秒重启一次，如果不加入规则运行是正常的。  这种情况遇到过吗？
重启的时候报错：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x969ab0]

![image](https://user-images.githubusercontent.com/8800072/102209414-adeb4800-3f0b-11eb-9e3c-cabc7b242d11.png)

![image](https://user-images.githubusercontent.com/8800072/102209490-c9565300-3f0b-11eb-9480-3328627dac29.png)

**Comment by 231bobo** [comment]
应该是某一条规则导致的，具体的哪一条还在排查。

**Comment by jayryu** [comment]
> 应该是某一条规则导致的，具体的哪一条还在排查。

是报警策略的问题，报警策略中不要填写odin group，值班组等不需要的信息

**Comment by 231bobo** [comment]
> > 应该是某一条规则导致的，具体的哪一条还在排查。
> 
> 是报警策略的问题，报警策略中不要填写odin group，值班组等不需要的信息

好的，谢谢。  已经去掉了这些信息，目前没有60秒重启容器报错了。  

【还有一点没想明白，以前这些信息存在，是稳定运行了很久的，但最近添加过一些规则后，开始两天没问题，后面突然就出现这个60s重启报错的问题。】

**Comment by xupengyao** [comment]
请问你删除规则后报警还会一直持续吗？ @231bobo

**Comment by 231bobo** [comment]
> 请问你删除规则后报警还会一直持续吗？ @231bobo

【是报警策略的问题，报警策略中不要填写odin group，值班组等不需要的信息】  按照这个，把一些无关的信息去掉后，就正常了。
