### ISSUE TITLE
匹配规则支持正则表达式吗

### ISSUE THREAD

**Issue by caoshitong369** [Qihoo360/doraemon#92]
![image](https://user-images.githubusercontent.com/44139321/102613587-b6db5400-416d-11eb-9215-4eb4b06f9e52.png)

**Comment by jayryu** [comment]
支持，prometheus支持就行

**Comment by caoshitong369** [comment]
但是我按照正则去设置报警规则没有效果，把正则去掉就可以，是不是不支持正则呢

**Comment by caoshitong369** [comment]
![image](https://user-images.githubusercontent.com/44139321/102859561-1041cc80-4467-11eb-91f9-e1440da99b38.png)
prometheus是支持正则的

**Comment by caoshitong369** [comment]
的确是支持的，谢谢
![Uploading image.png…]()
