### ISSUE TITLE
告警源无法添加！

### ISSUE THREAD

**Issue by sober-wang** [Qihoo360/doraemon#99]
![image](https://user-images.githubusercontent.com/35804630/109763499-21f4dc80-7c2d-11eb-8eed-95872c0b9842.png)

**Comment by stanxing** [comment]
我也是，部署好后自动登录的，然后添加数据源报错，报错内容是没有认证，请问是怎么解决的

**Comment by sober-wang** [comment]
必须使用 mysql:5.6.41 这个版本。而且，建议使用 docker-compose 部署

**Comment by stanxing** [comment]
我用 kubernetes 可以了，好像是我的 webUrl 没配置对，必须是跟外部域名以及协议一致
